-- AlterTable
ALTER TABLE "room_assignments" ADD COLUMN     "adultCount" INTEGER,
ADD COLUMN     "cnb11PlusCount" INTEGER,
ADD COLUMN     "cnb6To10Count" INTEGER,
ADD COLUMN     "cnbUnder6Count" INTEGER,
ADD COLUMN     "extraBedCount" INTEGER,
ADD COLUMN     "frozenSubtotal" DECIMAL(15,2),
ADD COLUMN     "frozenTotal" DECIMAL(15,2),
ADD COLUMN     "gstApplies" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "isFoc" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "mealPlanApCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "mealPlanCpCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "mealPlanMapdCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "mealPlanMaplCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "mealPlanOthersCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "negotiatedBreakfastRate" DECIMAL(15,2),
ADD COLUMN     "negotiatedDinnerRate" DECIMAL(15,2),
ADD COLUMN     "negotiatedExtraBedRate" DECIMAL(15,2),
ADD COLUMN     "negotiatedLunchRate" DECIMAL(15,2),
ADD COLUMN     "negotiatedRoomRate" DECIMAL(15,2),
ADD COLUMN     "occupantCount" INTEGER,
ADD COLUMN     "othersBreakfastPax" INTEGER,
ADD COLUMN     "othersDinnerPax" INTEGER,
ADD COLUMN     "othersLunchPax" INTEGER,
ADD COLUMN     "serviceChargeApplies" BOOLEAN NOT NULL DEFAULT true;
